# Generated by Django 3.2.6 on 2021-09-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
    ]
