# Generated by Django 3.2.6 on 2021-09-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210906_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='questions',
        ),
    ]
