# Generated by Django 3.2.6 on 2021-09-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210906_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
