# Generated by Django 3.2.6 on 2021-09-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='onsale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='onsale_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
